#!/usr/local/google/home/elhadik/NESS_GEMINI/venv/bin/python3
import sys
from mcp_atlassian import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
